---
ID: "43044e00-4ef4-4094-8b0c-794c3f8378cc"
Parent: "015434ec-c85a-40be-90a0-73e3f6de9e14"
Template: "015434ec-c85a-40be-90a0-73e3f6de9e14"
Path: /sitecore/templates/Project/MyTenant/Category/__Standard Values
DB: master
SharedFields:
- ID: "d4952280-2d7d-4bf4-a99a-ea36dad0f0a7"
  Hint: Body Css Class
  Value: "category-page"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}" />
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170201T111239Z
    - ID: "4c2f221f-9426-45ed-9eeb-c79bb3169565"
      Hint: StickyNotes
      Value: |
        {"items":[]}
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
