---
ID: "a084fa8a-56c1-4eae-89d5-76aef6a5e813"
Parent: "906a2ff8-3131-4ba7-a368-044d822098d6"
Template: "d36bae09-f787-4b31-bada-d830e0799257"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Catalog Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "453f14e4-1045-4e50-be74-dd0a89ee764a"
  Hint: ExcludeCategoriesFromSearchResults
  Type: Checkbox
  Value: 1
- ID: "48420f58-f1df-4b80-8386-b62aa84e9b57"
  Hint: Gift Card Page Link
  Value: |
    <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{82DD1D7F-EC3C-41D2-99A9-CEE90EE40AF7}" />
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{50E69E44-1425-4502-9589-4031F47DCD4F}"
- ID: "fc9c3c29-7a69-4088-8c89-22fb3d493a9a"
  Hint: GiftCardProductId
  Value: 6042986
- ID: "fdd0d6ae-bccd-4cd9-a078-3103d720d2e7"
  Hint: Use Direct Navigation
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Catalog Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T131456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
