---
ID: "eba470ce-1a7b-4009-ac96-54a9c6589950"
Parent: "6b3d3ff4-5123-47af-9e2b-c8b23100ba17"
Template: "d36bae09-f787-4b31-bada-d830e0799257"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Catalog Configuration
DB: master
SharedFields:
- ID: "453f14e4-1045-4e50-be74-dd0a89ee764a"
  Hint: ExcludeCategoriesFromSearchResults
  Type: Checkbox
  Value: 1
- ID: "48420f58-f1df-4b80-8386-b62aa84e9b57"
  Hint: Gift Card Page Link
  Value: |
    <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{CD76BC8F-48A7-4005-81B9-C84702CFA679}" />
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{50E69E44-1425-4502-9589-4031F47DCD4F}"
- ID: "fc9c3c29-7a69-4088-8c89-22fb3d493a9a"
  Hint: GiftCardProductId
  Value: 6042986
- ID: "fdd0d6ae-bccd-4cd9-a078-3103d720d2e7"
  Hint: Use Direct Navigation
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Catalog Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190812T103015Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
