---
ID: "00ecb3a8-951b-4a78-a9e2-22a2e1a0210d"
Parent: "6b3d3ff4-5123-47af-9e2b-c8b23100ba17"
Template: "9bb44636-1bd5-410c-86cb-b53663944cc3"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Storefront Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BE2D0F3D-9D02-4C9E-825E-C1C75573834C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190812T103015Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
