---
ID: "583d5ac2-1b0f-45ab-93bc-9143a7628ea7"
Parent: "3741ec48-a89c-4f04-ad42-3daf95e2eda7"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190808T121837Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
