---
ID: "6050659c-a5ac-46e9-8c03-50d44698adee"
Parent: "3d396c22-3ece-4bee-bddf-fdb3a128dfa1"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190812T102727Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
