---
ID: "9ce77770-d655-489d-8c50-fdb1d9b26af6"
Parent: "b2817955-a25f-40f7-889d-6253f3ea559f"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T111903Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
