---
ID: "c918bf87-155b-47c3-a42c-30dbc2d34a5b"
Parent: "f102fce3-bd46-4cd7-bc5b-c01d36d578cd"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T120449Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
