---
ID: "c7725735-0183-4030-ae27-5a9b3f7574e5"
Parent: "8c4c9ff0-eb7b-4f58-8810-cf59b316f9cd"
Template: "e1a3b30c-77bc-4f6c-a008-d01b3371235d"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Rendering Variants/Product Bundle
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/elements3.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181114T013753Z
