---
ID: "b12b370e-c716-4150-9d05-dd6a16bdedc2"
Parent: "58bcedd5-893e-4717-8e55-3d0b681f7c40"
Template: "e1a3b30c-77bc-4f6c-a008-d01b3371235d"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Rendering Variants/Product Bundle
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/elements3.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181114T013753Z
