---
ID: "8e4274f4-5f48-4e28-a3e1-c05b22b71d4b"
Parent: "0b1aea8a-ce71-4020-8bac-52b26eba4dda"
Template: "0b1aea8a-ce71-4020-8bac-52b26eba4dda"
Path: /sitecore/templates/Project/MyTenant/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190812T102217Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
