---
ID: "477bd99a-ec5c-4098-9628-c2ebae3b1cdf"
Parent: "2fd99c58-ddc4-416f-8ecc-46a40ddd6375"
Template: "2fd99c58-ddc4-416f-8ecc-46a40ddd6375"
Path: /sitecore/templates/Project/MyTenant/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T120037Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
