---
ID: "ab8860ff-2d69-4167-965c-2f4ad5030dec"
Parent: "9551d10e-466e-4b4f-a121-25d9de7cd649"
Template: "9551d10e-466e-4b4f-a121-25d9de7cd649"
Path: /sitecore/templates/Project/MyTenant/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190808T121419Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
