---
ID: "5d38e0d6-ee79-4e7c-b12e-6b21d2b13b48"
Parent: "6c01164e-1fb7-4bc9-8efb-d7bf5ae9b886"
Template: "6c01164e-1fb7-4bc9-8efb-d7bf5ae9b886"
Path: /sitecore/templates/Project/MyTenant/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T095458Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
