---
ID: "a57aa2df-9594-4346-9d48-12e0f201a985"
Parent: "32354b64-fa63-44ea-94ea-083dc09dbfed"
Template: "32354b64-fa63-44ea-94ea-083dc09dbfed"
Path: /sitecore/templates/Project/MyTenant/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T120039Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
