---
ID: "97e87a38-1194-4a3c-946b-05e287d455e5"
Parent: "50eebb2c-67d6-453e-869a-b739b88fd594"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/MyTenant/Storefront/Settings/Datasource Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190808T121830Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
